### ISSUE TITLE
Draft version of the novel being distributed by Amazon?

### ISSUE THREAD

**Issue by csides84** [morlockp/glomar_extractor#1]
Any chance that Amazon is sending out a draft version of Glomar Extractor? I thought maybe you were leaving easter eggs with the handful of typos since I did not notice any in _Caterpillar_, however, on page 11 I saw the following:

/* 

ROB: Again, this discussion is going to happen in the context of the "official" NASA estimates and the more trustworthy Project Osiris/Castle estimate. If you don't have time to scour book 2 for the numbers and don't mind me tweaking the text, I can edit it. 

TJIC: yes, please do 

*/ 

Similar comment shows up on page 13. 

Don't get me wrong, I like seeing behind the curtain, :-) but wanted to let you know just in case.

**Comment by morlockp** [comment]
Good catch, my apologies.

I've fixed this issue.
